services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    logging:
      driver: none
    networks:
      - blog-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  blog-backend:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
      # - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/blog?schema=public
      - PORT=5000
    depends_on:
      - db
    networks:
      - blog-network
    command: npm run start:dev

volumes:
  pgdata:

networks:
  blog-network:
    driver: bridge
