services:
  blog-backend:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DATABASE_URL="postgresql://admin:admin@localhost:5432/blog_db?schema=public"
      - PORT=5000
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog_db
    logging:
      driver: none
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
